#!/usr/bin/env bash
set -euo pipefail

# Sync OpenCode agents to Claude Code agent format.
# Source of truth: .opencode/agents/
# Output: .claude/agents/
# Skip list: .claude/agents/.manual (one agent name per line, no .md)

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC_DIR="$REPO_ROOT/.opencode/agents"
DST_DIR="$REPO_ROOT/.claude/agents"
MANUAL_FILE="$DST_DIR/.manual"

if [[ ! -d "$SRC_DIR" ]]; then
  echo "Error: $SRC_DIR not found" >&2
  exit 1
fi

mkdir -p "$DST_DIR"

# Load skip list
declare -A SKIP=()
if [[ -f "$MANUAL_FILE" ]]; then
  while IFS= read -r line; do
    line="${line%%#*}"        # strip comments
    line="${line// /}"        # strip spaces
    [[ -n "$line" ]] && SKIP["$line"]=1
  done < "$MANUAL_FILE"
fi

generated=0
skipped=0

for src_file in "$SRC_DIR"/*.md; do
  [[ -f "$src_file" ]] || continue
  name="$(basename "$src_file" .md)"

  # Check skip list
  if [[ -n "${SKIP[$name]:-}" ]]; then
    echo "  skip: $name (in .manual)"
    skipped=$((skipped + 1))
    continue
  fi

  # --- Parse frontmatter ---
  # Create a clean temp file (strip Windows \r)
  clean_file=$(mktemp)
  tr -d '\r' < "$src_file" > "$clean_file"
  trap "rm -f '$clean_file'" EXIT

  # Find the two --- delimiters
  first_delim=$(awk '/^---$/{print NR; exit}' "$clean_file")
  second_delim=$(awk -v start="$first_delim" 'NR>start && /^---$/{print NR; exit}' "$clean_file")

  if [[ -z "$first_delim" || -z "$second_delim" ]]; then
    echo "  warn: $name — could not parse frontmatter, skipping" >&2
    continue
  fi

  # Extract frontmatter block
  frontmatter=$(sed -n "$((first_delim+1)),$((second_delim-1))p" "$clean_file")

  # Extract description (everything after "description: ")
  description=$(echo "$frontmatter" | grep -m1 '^description:' | sed 's/^description:\s*//')

  # Extract model (default: sonnet)
  model=$(echo "$frontmatter" | grep -m1 '^model:' | sed 's/^model:\s*//' || true)
  model="${model:-opus}"

  # Extract tool booleans
  get_tool() {
    echo "$frontmatter" | grep -E "^\s+$1:" | awk '{print $2}' | tr -d '[:space:]' || echo "false"
  }
  tool_edit=$(get_tool "edit")
  tool_write=$(get_tool "write")
  tool_bash=$(get_tool "bash")
  tool_websearch=$(get_tool "websearch")

  # Build Claude Code tool list
  tools="Read, Glob, Grep"
  [[ "$tool_edit" == "true" ]] && tools="$tools, Edit"
  [[ "$tool_write" == "true" ]] && tools="$tools, Write"
  [[ "$tool_bash" == "true" ]] && tools="$tools, Bash"
  [[ "$tool_websearch" == "true" ]] && tools="$tools, WebSearch, WebFetch"

  # Extract body (after second ---)
  body=$(tail -n +"$((second_delim+1))" "$clean_file")

  # Write output
  dst_file="$DST_DIR/$name.md"
  cat > "$dst_file" <<EOF
---
name: $name
description: $description
tools: $tools
model: $model
---

<!-- AUTO-GENERATED by scripts/sync-agents.sh from .opencode/agents/$name.md — DO NOT EDIT MANUALLY -->
$body
EOF

  echo "  sync: $name → .claude/agents/$name.md  [$tools]"
  generated=$((generated + 1))
done

echo ""
echo "Done: $generated generated, $skipped skipped"
